--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/tduarte/Pictures/Wallpapers/IMG_5801-cropped.jpg"

-- Special
background="#0f1d2a"
foreground="#f4ebdc"
cursor="#f4ebdc"

-- Colors
color0="#0f1d2a"
color1="#D56278"
color2="#C0947A"
color3="#E0748A"
color4="#E79D9D"
color5="#F0ADBC"
color6="#ECCDA6"
color7="#f4ebdc"
color8="#aaa49a"
color9="#D56278"
color10="#C0947A"
color11="#E0748A"
color12="#E79D9D"
color13="#F0ADBC"
color14="#ECCDA6"
color15="#f4ebdc"
