# Shell variables
# Generated by 'wal'
wallpaper='/home/tduarte/Pictures/Wallpapers/IMG_5801-cropped.jpg'

# Special
background='#0f1d2a'
foreground='#f4ebdc'
cursor='#f4ebdc'

# Colors
color0='#0f1d2a'
color1='#D56278'
color2='#C0947A'
color3='#E0748A'
color4='#E79D9D'
color5='#F0ADBC'
color6='#ECCDA6'
color7='#f4ebdc'
color8='#aaa49a'
color9='#D56278'
color10='#C0947A'
color11='#E0748A'
color12='#E79D9D'
color13='#F0ADBC'
color14='#ECCDA6'
color15='#f4ebdc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
